// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten by subsequent CLI re-runs.
const awsmobile = {
    "aws_project_region": "ap-southeast-1", // Your AWS Region (e.g., "us-east-1", "ap-southeast-1")
    "aws_cognito_region": "ap-southeast-1", // Your AWS Region
    "aws_user_pools_id": "ap-southeast-1_71t1gF260", // e.g., "ap-southeast-1_xxxxxxxxx"
    "aws_user_pools_web_client_id": "60d6ge0bbmt0ghn02s0m2u5jd2", // e.g., "xxxxxxxxxxxxxxxxx"
    "aws_mandatory_sign_in": "enable",
    "aws_cloud_logic_custom": [
        {
            "name": "BookmarkApi", // This is the arbitrary API name you'll use in Amplify.
                                   // Keep it consistent with your API Gateway configuration.
            "endpoint": "https://xqbffhxs2d.execute-api.ap-southeast-1.amazonaws.com/Prod/", // e.g., "https://xxxxxxxxxx.execute-api.ap-southeast-1.amazonaws.com/Prod"
            "region": "ap-southeast-1" // Your AWS Region
        }
    ]
};

export default awsmobile;